version: '3'
 
services:
  mdanwebfront:
    build:
      context: ./mdanwebfront
    ports:
      - "80:80"
    depends_on:
      - mdanfastapi
    networks:
      - mdannetwork
 
  mdanfastapi:
    build:
      context: ./mdanfastapi
    ports:
      - "8000:8000"
    depends_on:
      - mdanpostgreSQL
    environment:
      - DATABASE_URL=postgresql://postgres:password@mdanpostgreSQL:5432/mydatabase
    networks:
      - mdannetwork
 
  mdanpostgreSQL:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_HOST: mdanpostgreSQL
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - mdannetwork
 
networks:
  mdannetwork:
    driver: bridge
 
volumes:
  postgres_data: