version: '3'
networks:
  wordpress: {}

services:
  mdanwebfront:
    build:
      context: ./mdanwebfront
    ports:
      - "80:80"
    depends_on:
      - mdanfastapi

  mdanfastapi:
    build:
      context: ./mdanfastapi
    ports:
      - "8000:8000"
    depends_on:
      - mdanpostgreSQL
    environment:
      - DATABASE_URL=postgresql://postgres:password@mdanpostgreSQL:5432/mydatabase
    networks: 
      - wordpress

  mdanpostgreSQL:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:

